### ISSUE TITLE
你好。在国内的镜像有吗？

### ISSUE THREAD

**Issue by BendyXu** [BubblingXuYijie/secure-api-spring-boot#1]
你好。在国内的镜像有吗？

**Comment by BubblingXuYijie** [comment]
Gitee：https://gitee.com/BubblingXuYijie/secure-api-spring-boot

**Comment by BendyXu** [comment]
![image](https://github.com/BubblingXuYijie/secure-api-spring-boot/assets/7719425/c6b95ba1-0a25-414d-880e-1457ea2507d6)
![image](https://github.com/BubblingXuYijie/secure-api-spring-boot/assets/7719425/02ff8a76-332f-44c6-8681-f1de1b38c216)
我在接口上加了注解，但是在返回值上并不生效

**Comment by BubblingXuYijie** [comment]
> ![image](https://private-user-images.githubusercontent.com/7719425/344867744-c6b95ba1-0a25-414d-880e-1457ea2507d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTQ2OTAsIm5iZiI6MTcxOTg5NDM5MCwicGF0aCI6Ii83NzE5NDI1LzM0NDg2Nzc0NC1jNmI5NWJhMS0wYTI1LTQxNGQtODgwZS0xNDU3ZWEyNTA3ZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMDQyNjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjYyZTJiOTNmZmFmZjg1OWY5MTBmYzUyZWQ2ZTU2ZGUyMDg0NjUwMTY2MDNmZTFjMmIxYWQ2MDU4MjEyMDE1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KudHJR_99qaMsvBwcgx3QBRDzyOiBmCU3lVQvu1ms8A) ![image](https://private-user-images.githubusercontent.com/7719425/344867870-02ff8a76-332f-44c6-8681-f1de1b38c216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTQ2OTAsIm5iZiI6MTcxOTg5NDM5MCwicGF0aCI6Ii83NzE5NDI1LzM0NDg2Nzg3MC0wMmZmOGE3Ni0zMzJmLTQ0YzYtODY4MS1mMWRlMWIzOGMyMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMDQyNjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI3MGE3ZjFmMjg1MmI0Y2EzZmVkNjQwYjQwNDFmOWE0NmFkNzBkN2I3NjVkOWI2NDQ4NTcyMDk4OWRiMWJlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4gf0OjwZUFDfWNC0ONiIt0UHWVhCpNyNbln8ns6UuSo) 我在接口上加了注解，但是在返回值上并不生效

你好，版本号是多少，参数解密生效吗，返回值返回的是明文？

**Comment by BendyXu** [comment]
springboot 2.6.8 
secure-api-spring-boot 2.0.8
返回值是明文

**Comment by BubblingXuYijie** [comment]
不好意思，已修复，原因是spring boot 2.6 版本及以下的自动注入方式有些不同，已发布 2.0.9 版本，大概1-2小时后可以下载

**Comment by BubblingXuYijie** [comment]
> springboot 2.6.8 secure-api-spring-boot 2.0.8 返回值是明文

你好，2.0.9 版本已经可以下载了，试试看

**Comment by BendyXu** [comment]
你好，我在仓库里还没看到2.0.9, 你是用哪个镜像地址

**Comment by BubblingXuYijie** [comment]
> 你好，我在仓库里还没看到2.0.9, 你是用哪个镜像地址

发到 spring boot 2 这个分支了

**Comment by BubblingXuYijie** [comment]
> 你好，我在仓库里还没看到2.0.9, 你是用哪个镜像地址

maven中央仓库同步显示需要1-2天，现在你直接引就行，能下载的
<dependency>
    <groupId>icu.xuyijie</groupId>
    <artifactId>secure-api-spring-boot-starter</artifactId>
    <version>2.0.9</version>
</dependency>

**Comment by BendyXu** [comment]
![image](https://github.com/BubblingXuYijie/secure-api-spring-boot/assets/7719425/3ed2485e-71e7-4f1d-822a-55a1dd3adf52)
已经下载到2.0.9版本，但是似乎还是没生效

**Comment by BubblingXuYijie** [comment]
![image](https://github.com/BubblingXuYijie/secure-api-spring-boot/assets/45624106/f4580ccc-ce7e-4f07-9fb2-34f4b6765e67)
![image](https://github.com/BubblingXuYijie/secure-api-spring-boot/assets/45624106/5ee6d522-1df6-4777-ba98-5af1feb8e701)

我模拟了你的代码环境是ok的，你看一下你的怎么starter是2.0.9而autoconfig是2.0.8呢，这俩模块是项目依赖的，你引用starter以后会自动引入相同版本的autoconfig，你是不是手动引了一个2.0.8的autoconfig，还是什么其他问题

**Comment by BubblingXuYijie** [comment]
> ![image](https://private-user-images.githubusercontent.com/7719425/344951107-3ed2485e-71e7-4f1d-822a-55a1dd3adf52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTA3MjksIm5iZiI6MTcxOTkxMDQyOSwicGF0aCI6Ii83NzE5NDI1LzM0NDk1MTEwNy0zZWQyNDg1ZS03MWU3LTRmMWQtODIyYS01NWExZGQzYWRmNTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMDg1MzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjRmZjViNmU1NmZlYTljMzhiODE3Mzc1MzFiZWEwNGE0ODQ3OTJlMzE1NDkzZTYyZDRjNjFhYzhiM2ZkNmU5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ltwD6q5AT3zeNI9kAmXZezea9LNgN_xD5tYKBcc4Tys) 已经下载到2.0.9版本，但是似乎还是没生效

![image](https://github.com/BubblingXuYijie/secure-api-spring-boot/assets/45624106/422cfac7-2ef3-4952-a967-b2648292b0c1)
你应该是这样搞的吧，这样确实不行，只需要引入secure-api-spring-boot-starter就ok了哈

**Comment by BendyXu** [comment]
可以了。谢谢，是我这里手动配置了autoconfigure 的版本2.0.8
