### ISSUE TITLE
是否可以支持 @ParameterObject 注解（支持Date、LocalDateTime等日期格式化和相关配置）

### ISSUE THREAD

**Issue by imswy** [BubblingXuYijie/secure-api-spring-boot#10]
对于使用了@ParameterObject注解的接口,参数解密出来的都是null

**Comment by BubblingXuYijie** [comment]
我按照你的，嵌套实体类，加valid校验，加parameterObject注解试了一下，还是好的，你看看你的日志打印的 “加密前：null”，说明你的参数没有接收到，是不是前端传参有问题还是什么，你先把加密功能关了，你看看正常能不能收到参数

![image](https://github.com/user-attachments/assets/759726b3-1d1a-4ab9-a0d4-b5dc78ebbed7)

**Comment by imswy** [comment]
关闭加密功能是可以收到参数,我先研究看看

**Comment by imswy** [comment]
![微信截图_20240806151352](https://github.com/user-attachments/assets/d6618e12-a250-4dbe-a688-60037cb3fbd2)
![微信图片_20240806151452](https://github.com/user-attachments/assets/b72f2869-02df-4361-97fb-31d436b7bfb2)
前端通过axios将整个params加密后,传到后端的格式变成了0=xxx了,现在改成了只对params参数的值加密就好了

另外转换Json对象时,jackson默认不支持LocalDateTime类型,会失败

**Comment by BubblingXuYijie** [comment]
对的，param参数就是要只对值加密，如果你想加密整个参数体，前端要发送用json格式参数，后端用@RequestBody接收那种，jackson这个确实，需要配置，我下个版本增加一下LocalDateTime支持

**Comment by BubblingXuYijie** [comment]
对日期格式化的支持，版本已发布 2.1.6 / 3.0.9，增加了Date和LocalDateTime等格式化pattern配置，文档中有示例，默认 yyyy-MM-dd HH:mm:ss
