### ISSUE TITLE
接口入参为Map类型获取不到数据

### ISSUE THREAD

**Issue by wangzhengliang** [BubblingXuYijie/secure-api-spring-boot#11]
接口入参为Map类型时使用@RequestParam可以接受到数据，但是数据不能解密；使用@DecryptParam时对应map参数获取不到任何数据

**Comment by BubblingXuYijie** [comment]
我这里测试是正常的，可以提供一下 secureApi 的版本和 spring boot 的版本吗，还有你的map明文、密文和密钥

这是我的解密结果：

![image](https://github.com/user-attachments/assets/2921af59-9f6e-4d97-8a44-b0355f981e1a)

这是我的传值：

![image](https://github.com/user-attachments/assets/bf51ca28-5782-4a62-a055-779123745b09)

**Comment by BubblingXuYijie** [comment]
我这里测试是正常的，可以提供一下 secureApi 的版本和 spring boot 的版本吗，还有你的map明文、密文和密钥

这是我的解密结果：

![image](https://github.com/user-attachments/assets/03d14afd-f422-4ef5-a39f-674d4dd5d39d)


这是我的传值：

![image](https://github.com/user-attachments/assets/6a0992ac-a53f-4abd-8873-dcbffe89af2c)

**Comment by wangzhengliang** [comment]
我是这样传值的：
![image](https://github.com/user-attachments/assets/e9013f07-e5b7-48c4-9841-7681e576f101)

参数值：
page=EBRTNbaOFe2BfHds4PuJGg&limit=RiteTI1htBnPxagLkyll8w&username=xOgjlWUvso2aLdziVuvu9w&shopName=xOgjlWUvso2aLdziVuvu9w

这样接收参数的：
![image](https://github.com/user-attachments/assets/9b44dd36-5860-4bf1-b467-4d9fe1a2063b)

在参数解析的时候直接报错：
![image](https://github.com/user-attachments/assets/f2f92b9b-05c3-48cf-a050-6dcb8f5db6c2)

加密参数：
cipher-algorithm: aes_cbc_pkcs5
key: oURKtBcNU6axnNoebKkuPqkCn6ivhE9qbg9FpeNnfpo=
iv: eW1xeThJSkprcEZUTGh1Ng==

**Comment by BubblingXuYijie** [comment]
兄弟，提供一下 secureApi 的版本和 spring boot 的版本，因为spring boot各版本参数处理问题我修改了几次，看看你是什么版本

**Comment by wangzhengliang** [comment]
spring boot版本：2.6.11
secure api版本：2.1.6

**Comment by BubblingXuYijie** [comment]
哦看了你的传值才反应过来，@RequestParam能把你的参数param解析成一个map放进去，但目前@DecryptParam注解没有这个功能，你这个传值现在controller只能这样ba把参数分开写：

![image](https://github.com/user-attachments/assets/8a87de4a-cc3c-40dd-ab15-7b60f30b998a)

参数太多不想写那没多@DecryptParam注解可以配置url匹配，想写一起的话可以把字段放在一个实体类中，使用@DecryptParam标记实体类中你想解密的字段：

![image](https://github.com/user-attachments/assets/438b1944-78f0-49b6-9093-f84c5d9f3281)

![image](https://github.com/user-attachments/assets/9c40b50e-3beb-4dcf-845a-81686c71c61a)

![image](https://github.com/user-attachments/assets/479b9c97-5c7d-44a8-a033-129384999c89)

还可以使用@DecryptApi整体解密@RequestBody参数。传值的时候传一个实体类json串加密后的密文就可以：

![image](https://github.com/user-attachments/assets/3b452427-34b6-43a7-b807-d4f4b711ff13)

![image](https://github.com/user-attachments/assets/1be8bc78-06fb-4614-8ade-558cd218520f)

![image](https://github.com/user-attachments/assets/ddd1d50e-cea4-4320-a0a9-ecd57b611c7e)

**Comment by wangzhengliang** [comment]
嗯嗯，好的，谢谢解答。
我维护的是一个老项目，新加入的接口数据加解密功能。测试的时候其他情况是正常的，就是部分接口直接使用map接收前端key=value类型的数据有问题。本来是不打算改原有项目代码的，现在看来还是必须要改下了  T_T~~~

**Comment by BubblingXuYijie** [comment]
改吧，为团队做贡献，用map接收key-value确实不合规范哈哈哈
