### ISSUE TITLE
参数为时间格式的集合时解析有问题

### ISSUE THREAD

**Issue by imswy** [BubblingXuYijie/secure-api-spring-boot#12]
![微信截图_20240823150503](https://github.com/user-attachments/assets/0395f548-f632-4c4e-8440-bb8234bbd7ff)

**Comment by BubblingXuYijie** [comment]
感谢反馈，已修复，版本已发布：2.1.7 / 3.1.0

**Comment by imswy** [comment]
![微信图片_20240826135350](https://github.com/user-attachments/assets/d5111f3e-47ab-4208-91a4-41d77b411db4)
前端加密后发送请求时就是字符串,为什么这里要处理 " 呢?
3.9版本后会造成StringIndexOutOfBoundsException

**Comment by BubblingXuYijie** [comment]
因为。。。你看，如果用户要加密对象，那么要把对象会先转为string再进行加密对吧，而List转为String以后，再转回List会多出引号，你存入的是字符串 1，但是会还原成了字符串 “1”，后面我看看换用objectmapper反序列化还原吧，就不用处理引号了，上班挺忙改的比较匆忙，这周给他好好整整

![image](https://github.com/user-attachments/assets/23eb5127-d0e4-4383-8203-1c1411f07d41)

**Comment by BubblingXuYijie** [comment]
昨天看错了，你这个截图里要处理引号是因为json字符串两边就是带引号的，比如postman传参时，不带格式会报错，你这个不带的情况第一次遇到，做了兼容，版本已发布 2.1.8 / 3.1.1

![image](https://github.com/user-attachments/assets/bb74eb8f-966e-4ada-8248-3dce65a58151)
