### ISSUE TITLE
在POM被引入之后，配置文件yml没配置，还是会默认开启加密，而且密码随机。

### ISSUE THREAD

**Issue by BendyXu** [BubblingXuYijie/secure-api-spring-boot#7]
在多模块共用lib的时候，有些模块是不需要加密，希望能优化一下。

**Comment by BubblingXuYijie** [comment]
这个默认是开启的，需要在yml配置下enabled为false，下个版本确实可以改成默认关闭，这样合理点。

然后多模块公用lib，你的多模块里面有很多web api模块吗？这个组件只会对标记了@RestController和@Controller的请求参数和返回值进行作用，其他非web模块不会生效的，如果真有很多个web模块，那配置文件也是多份吧，不需要加密的模块配置文件设置enabled为false就行了呀

**Comment by BendyXu** [comment]
我就是想临时关闭某些模块的加密，结果配置enabled为false不生效，然后全部注释掉配置文件也默认开启着。最后只能移除lib里面的jar包。

**Comment by BubblingXuYijie** [comment]
下个版本默认关闭吧，你只要不加注解、不配置url匹配，他就什么都不会做，只是给你打印个开启加密的提示日志

**Comment by BubblingXuYijie** [comment]
版本 2.1.3 / 3.0.6 已发布，默认关闭了组件功能
