### ISSUE TITLE
使用RSA,当数据过大时,需要分段加密和解密

### ISSUE THREAD

**Issue by weiyong6230** [BubblingXuYijie/secure-api-spring-boot#8]

**Comment by BubblingXuYijie** [comment]
好的，这个倒是没注意，等俺研究一下

**Comment by weiyong6230** [comment]
密钥位数为2048时,加密的明文最大不能超过245,解密最大不能超过256.因此是否可以将密钥位数做成一个配置,加解密就可以根据密钥位数判断是否进行分段加密了.分段加密方式可参考[](https://www.cnblogs.com/YellowJesse/p/15411664.html)

**Comment by BubblingXuYijie** [comment]
分段加密功能已发布，版本 2.1.5 / 3.0.8

**Comment by weiyong6230** [comment]
测试没有问题,感谢大佬!
